### PR TITLE
Fix Installer generated by HCC (BUG)

### LINKED ISSUE #412: Installer generated by HCC (BUG)
## Describe the bug
After downloading the Hotcakes Commerce repository and building in Debug mode to restore all dependencies, when we switch to Release mode to Build again and generate the HCC installer, the installation generated when trying to install it in a clean DNN solution shows us a mistake. The Hotcakes.Shipping.Ups.Keys.dll is missing from the installer.

## Software Versions
- DNN: 09.10.02
- Hotcakes:  03.06.00

## To Reproduce
1. Clone the Hotcake GitHub repository.
2. Open the solution with administrator permissions.
3. Rebuild to download and install all dependencies.
4. Change the solution to Release Mode and recompile to generate the installer.
5. Install the installer in a DNN solution (hotcakes-commerce-core-development\\_Install\HotcakesCommerce_03.06.00_Core_Install.zip).

## Expected behavior
The installer generated in release mode must be installed in a solution correctly

## Actual behavior
A DLL is missing within the installer and fails to install in the DNN solution

## Screenshots
imagen

### PR DESCRIPTION
**Pull request by ArielBlanco1990**
Removed unnecessary assembly reference within the manifest.

Fixed #412

### CODE REVIEW

**Comment by WillStrohl** [comment]
FYI - This isn't the correct fix for this issue.  If the DLL is missing, the fix isn't to remove the code that expects it to be there.  The code should be updated to be sure to move the DLL.  This is most likely a bug in the build process, not the DNN manifest.  

The way this PR is done, the DLL still won't be copied, but DNN won't complain about it, because there isn't a reference to it.

**Comment by ArielBlanco1990** [comment]
I was reviewing the previous Releases of Hotcakes and there was a library with the name Hotcakes.Shipping.Ups.Keys

03 02 03_Librarys

this was removed in the last release

03 06 00_Libraries

but they forgot to remove the reference inside the manifest, so when we try to install the extension we get this error.

03 06 00_Manifest_Lost_DLL

As shown it seems that this library was removed in some update

It may have happened here: Replace Ups registration with login #398

**Comment by WillStrohl** [comment]
Ah!  Thank you for pointing that out.  I (obviously) completely missed that.  😎

**Review by WillStrohl — APPROVED** [review]
Looks good!

**Comment by ArielBlanco1990** [comment]
The FindManyWithCache commit was an error, so it was reverted. As the PullRequest Fix Installer generated by HCC (BUG) #413 was approved but was not merged, the new change was added within the same branch. I reverted the change and created a new branch with the new changes.

**Pull request merged**
