### PR TITLE
Issue #166 - Using Stripe tokenization to send credit card information for processing

### PR DESCRIPTION
**Pull request by joshgk00**

### CODE REVIEW

**Comment by hismightiness** [comment]
Thank you for the PR.  Relating to Issue #166.

**Comment by hismightiness** [comment]
Hello @joshgk00 :

Have you tested this yourself yet?  I'm looking at merging this tonight?  I'll be testing this myself, but I wanted to see what kind of tests you may have run so far.

**Comment by joshgk00** [comment]
Yes, I've run some tests with valid and invalid cards. So far all seems to be working. I have a client that has been using the change in their production for almost a year now. No reported issues so far.

**Comment by hismightiness** [comment]
Outstanding to know!  I'll be doing the rest of the review and merging process later today or this evening.  Thanks again!

**Comment by hismightiness** [comment]
This looks good, Josh.  Great job!

**Pull request merged**
