### PR TITLE
Issue #63 - Update Regular Expression For Checking Email

### PR DESCRIPTION
**Pull request by moslem7026**
updated regular expression  to allow  newer domain name variations to pass validation.

### CODE REVIEW

**Comment by moslem7026** [comment]
why this pull request not applied in new versions ?

**Comment by moslem7026** [comment]
it doesnt seems good ,not to hear Community voice !

**Comment by hismightiness** [comment]
It takes time to review, test, and approve unexpected pull requests.  Is there an issue created for this?  Also, can you please provide details about what is broken and fixed with this update?

**Comment by moslem7026** [comment]
issue number #63  , Regex Expression has been re-write to support ICANN-era generic top-level domains

**Comment by hismightiness** [comment]
Do you have any test cases you can provide so that we can test this update before we include it into the release?

**Comment by hismightiness** [comment]
@moslem7026 I want to begin processing these in the next week or so. Can you please update this PR to be against the `development` branch and not the `master` branch.

**Pull request merged**
