### PR TITLE
Not autocomplete credit cards

### PR DESCRIPTION
**Pull request by VAlmea**
Update the remaining partial views

### CODE REVIEW

**Review by WillStrohl — CHANGES_REQUESTED** [review]
Your update just made me research the `autocomplete` attribute, and I now realize that we have different updates to make.  

[HTML Attribute: autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)  

The `cc-csc` value you added is good, but it needs to be in the CCV field, not in the credit card number field, where you put it.  The credit card number instead uses the value of `cc-number` .  

In addition, the name and date fields also have unique values that have been built for this kind of use case.  

Please review the documentation above and update your PR appropriately in both the core of HCC and also the client viewset.

**Comment by WillStrohl** [comment]
@VAlmea This one too...   Can you please respond confirming whether or not this is ready now?  I submitted a review nearly a month ago.  :(

**Comment by VAlmea** [comment]
Will, When I made the changes requested by you the browser popup to save the card number keeps coming up, which is not the expected behavior, the cc-csc value makes the browser see this field as CCV type, which cannot be saved by the browser

**Review by WillStrohl — APPROVED** [review]
Looks good!

**Pull request merged**
