### PR TITLE
Uninstall Leaves Artifacts

### PR DESCRIPTION
**Pull request by ArielBlanco1990**
Update Uninstall Method in HotcakesController and fix SqlDataProvider, to completely remove Hotcakes folder under DesktopModule, dll files & HCC Table.

### CODE REVIEW

**Comment by ArielBlanco1990** [comment]
BugFix. Fixes #400

**Review by WillStrohl — COMMENTED** [review]
As far as I can tell, there are two actual updates here.  

1. There is additional code added to the `HotcakesController`.  
2. The SQL code had two things moved to the end. 

The rest is just white space updates.  Am I correct?

**Comment by WillStrohl** [comment]
@ArielBlanco1990 I just wanted to ping you again... I left a comment for you here.  :)

**Comment by ArielBlanco1990** [comment]
@WillStrohl That's right, those are the 2 changes.  Codes added to the HotcakesControler and in the SqlProvider two things moved to the end.

**Pull request merged**
