### PR TITLE
Adding missing Xcillion Skin

### PR DESCRIPTION
**Pull request by joshgk00**
I was setting up a new dev environment for HCC and got my database setup according to the docs. When I went to run the development website I this DNN error

`[D:2][T:9][ERROR] DotNetNuke.Services.Exceptions.Exceptions - DotNetNuke.Services.Exceptions.PageLoadException: Unhandled error loading page. ---> System.Web.HttpException: The file '/Portals/_default/Skins/Xcillion/Inner.ascx' does not exist.`

Looks like the default Skin was missing from the repo. 

This change will add the missing skin folder to the repo to resolve the above mentioned error when setting up a new dev environment

### CODE REVIEW

**Comment by hismightiness** [comment]
This looks like you added and then deleted the PR changes.  Was that intentional?

**Comment by joshgk00** [comment]
This wasn't intentional. I can submit another PR for this change.  Might be easier than trying to fix whatever I did on this PR

**Comment by hismightiness** [comment]
Yes. Maybe that will be better.  :)  Thanks!

**Comment by WillStrohl** [comment]
Hmmm...  It looks like this could be safely closed now.  Am I seeing that correctly?  🤔

**Pull request closed without merging**
