### PR TITLE
Issue 340

### LINKED ISSUE #340: Product Viewer does not display product details without "slug" in url
## Describe the bug
Product Viewer does not display product details without "slug" in url. i.e.

www.mysite.com/store/product-viewer/product1
This url does not display the product

www.mysite.com/store/product-viewer/slug/product1
This url does display the product

The urls generated by the Category Viewer don't include slug and this is what we'd expect.

## Software Versions
- DNN:  09.06.00
- Hotcakes:  03.05.00

## To Reproduce
1. On Dnn site, add Culture - English (United Kingdom) and make default and disable English (United States)
2. Install fresh version of HC 3.5.0 and run through setup wizard using defaults and let it create the relevant pages.
3. Add product category and product
4. View the Category Viewer page and click on the product
5. Product viewer page is blank

## Expected behavior
Product Viewer page should display the product using the urls from the Category Viewer page

## Actual behavior
Product Viewer page does not show product details.

### PR DESCRIPTION
**Pull request by moslem7026**
Fix #340

### CODE REVIEW

**Review by erw13n — COMMENTED** [review]
All this change is not necessary, pls commit only a clean version of it.

**Review by hismightiness — CHANGES_REQUESTED** [review]
@moslem7026  Please see the comment by @erw13n

**Comment by hismightiness** [comment]
Hello @moslem7026 ...  Can you please resolve this PR or create a new one?  This one can't be merged as-is.

**Comment by moslem7026** [comment]
> Hello @moslem7026 ... Can you please resolve this PR or create a new one? This one can't be merged as-is.

I will submit new Pull Request

**Comment by hismightiness** [comment]
@moslem7026 Thank you.  I'm not sure I understand the other part of your comment though.  Would it be okay to close this PR now?

**Pull request closed without merging**
